# Generated by Django 4.1.7 on 2023-04-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cost', models.DecimalField(decimal_places=0, default='', max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=0, default='', max_digits=5)),
            ],
        ),
    ]
