# Generated by Django 4.1.7 on 2023-04-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mari_efficiency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
