# Generated by Django 4.1.7 on 2023-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mari_efficiency', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
