# Generated by Django 4.1.7 on 2023-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mari_efficiency', '0004_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ENH', 'Enhancement'), ('WT/TR', 'Wartorn/Trade')], default='', max_length=20),
        ),
    ]
